-- ============================================================================
-- Peru Market ERP — Esquema completo para Supabase (PostgreSQL)
-- ----------------------------------------------------------------------------
-- Conversión de `perumarket_erp - origin.sql` (MariaDB) a PostgreSQL.
--
-- CÓMO USARLO:
--   1. Supabase → SQL Editor → New query
--   2. Pega TODO este archivo y ejecuta (RUN).
--   3. Luego ejecuta `seed.sql` para cargar los datos.
--   4. Crea tu usuario admin (ver el final de este archivo / README).
--
-- Notas de conversión:
--   * enum(...)            -> text + CHECK
--   * tinyint(1)           -> boolean
--   * int AUTO_INCREMENT   -> bigint generated by default as identity
--   * decimal(p,s)         -> numeric(p,s)
--   * timestamp ON UPDATE  -> timestamptz + trigger set_updated_at()
--   * Se mantienen los MISMOS nombres de tablas/columnas que el original.
-- ============================================================================

-- Limpieza idempotente (puedes re-ejecutar este script sin problemas)
drop schema if exists public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;

-- ----------------------------------------------------------------------------
-- Trigger genérico para `fecha_actualizacion`
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.fecha_actualizacion := now();
  return new;
end;
$$;

-- ============================================================================
-- TABLAS BASE (sin dependencias)
-- ============================================================================

create table public.persona (
  id                  bigint generated by default as identity primary key,
  tipo_documento      varchar(255),
  numero_documento    varchar(255),
  nombres             varchar(255),
  apellido_paterno    varchar(255),
  apellido_materno    varchar(255),
  correo              varchar(255),
  telefono            varchar(255),
  fecha_nacimiento    date,
  direccion           varchar(255),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.rol (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(255) not null,
  descripcion         varchar(255),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.modulo (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(255) not null,
  descripcion         varchar(255),
  ruta                varchar(255),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.categoria_producto (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(100) not null,
  descripcion         varchar(200),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.almacen (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(100) not null,
  codigo              varchar(20),
  direccion           varchar(200),
  capacidad_m3        numeric(10,2),
  responsable         varchar(100),
  estado              varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO')),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.departamento (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(100) not null,
  descripcion         varchar(150),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.metodo_pago (
  id                  bigint generated by default as identity primary key,
  nombre              varchar(50) not null,
  descripcion         varchar(150),
  estado              varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO')),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.ruta (
  id                    bigint generated by default as identity primary key,
  nombre                varchar(100) not null,
  origen                varchar(150),
  destino               varchar(150),
  distancia_km          numeric(10,2),
  tiempo_estimado_horas numeric(5,2),
  costo_base            numeric(10,2),
  fecha_creacion        timestamptz not null default now(),
  fecha_actualizacion   timestamptz not null default now()
);

create table public.vehiculo (
  id                  bigint generated by default as identity primary key,
  placa               varchar(20) not null,
  marca               varchar(50),
  modelo              varchar(50),
  capacidad_kg        numeric(10,2),
  estado              varchar(20) default 'DISPONIBLE' check (estado in ('DISPONIBLE','EN_RUTA','MANTENIMIENTO','INACTIVO')),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.proveedor (
  id                  bigint generated by default as identity primary key,
  ruc                 varchar(20) not null,
  razon_social        varchar(150) not null,
  contacto            varchar(100),
  telefono            varchar(20),
  correo              varchar(120),
  direccion           varchar(150),
  estado              varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO')),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

-- ============================================================================
-- TABLAS CON DEPENDENCIAS
-- ============================================================================

create table public.cliente (
  id                  bigint generated by default as identity primary key,
  id_persona          bigint not null references public.persona(id) on delete cascade,
  tipo                varchar(20) default 'NATURAL' check (tipo in ('NATURAL','JURIDICA')),
  estado              varchar(20) default 'ACTIVO',
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.conductor (
  id                  bigint generated by default as identity primary key,
  id_persona          bigint not null references public.persona(id) on delete cascade,
  licencia            varchar(20) not null,
  categoria_licencia  varchar(10),
  estado              varchar(20) default 'ACTIVO',
  nombres             varchar(100),
  apellido_paterno    varchar(100),
  apellido_materno    varchar(100),
  telefono            varchar(20),
  numero_documento    varchar(20),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.empleado (
  id                  bigint generated by default as identity primary key,
  id_persona          bigint not null references public.persona(id) on delete cascade,
  departamento_id     bigint references public.departamento(id),
  puesto              varchar(100),
  sueldo              numeric(10,2),
  fecha_contratacion  date,
  foto                varchar(255),
  cv                  varchar(255),
  estado              varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO')),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

-- usuario: enlazado a Supabase Auth mediante auth_user_id
create table public.usuario (
  id                  bigint generated by default as identity primary key,
  id_persona          bigint not null references public.persona(id) on delete cascade,
  id_rol              bigint not null references public.rol(id),
  username            varchar(255) not null,
  password            varchar(255),                       -- legacy; Supabase Auth gestiona la real
  estado              varchar(255) not null default 'ACTIVO',
  auth_user_id        uuid unique references auth.users(id) on delete set null,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.role_module_permissions (
  id                  bigint generated by default as identity primary key,
  id_rol              bigint not null references public.rol(id) on delete cascade,
  id_modulo           bigint not null references public.modulo(id) on delete cascade,
  has_access          boolean default false,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now(),
  unique (id_rol, id_modulo)
);

create table public.producto (
  id                      bigint generated by default as identity primary key,
  nombre                  varchar(150) not null,
  descripcion             text,
  sku                     varchar(50),
  precio_venta            numeric(10,2) default 0.00,
  precio_compra           numeric(10,2),
  stock                   integer default 0,
  stock_minimo            integer default 10,
  stock_maximo            integer default 1000,
  unidad_medida           varchar(20) default 'UNIDAD',
  peso_kg                 numeric(10,3),
  imagen                  varchar(255),
  categoria_id            bigint references public.categoria_producto(id),
  requiere_codigo_barras  boolean default true,
  estado                  varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO','CATALOGO')),
  fecha_creacion          timestamptz not null default now(),
  fecha_actualizacion     timestamptz not null default now()
);

create table public.codigo_barras (
  id                  bigint generated by default as identity primary key,
  codigo              varchar(50) not null,
  id_producto         bigint not null references public.producto(id) on delete cascade,
  id_proveedor        bigint references public.proveedor(id),
  tipo_codigo         varchar(20) default 'EAN13' check (tipo_codigo in ('EAN13','EAN8','UPC','CODE128','CODE39','QR','INTERNO')),
  descripcion         varchar(200),
  es_principal        boolean default false,
  unidades_por_codigo integer default 1,
  estado              varchar(20) default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO')),
  fecha_generacion    timestamptz not null default now(),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.proveedor_producto (
  id                  bigint generated by default as identity primary key,
  id_proveedor        bigint not null references public.proveedor(id) on delete cascade,
  id_producto         bigint not null references public.producto(id) on delete cascade,
  precio_compra       numeric(10,2),
  tiempo_entrega_dias integer,
  es_principal        boolean default false,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.inventario (
  id                  bigint generated by default as identity primary key,
  id_producto         bigint not null references public.producto(id) on delete cascade,
  id_almacen          bigint not null references public.almacen(id) on delete cascade,
  stock_actual        integer default 0,
  stock_minimo        integer default 0,
  stock_maximo        integer,
  ubicacion           varchar(50),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.compra (
  id                  bigint generated by default as identity primary key,
  id_proveedor        bigint not null references public.proveedor(id),
  id_almacen          bigint not null references public.almacen(id),
  id_usuario          bigint not null references public.usuario(id),
  fecha               timestamptz not null default now(),
  tipo_comprobante    varchar(20) default 'ORDEN_COMPRA' check (tipo_comprobante in ('FACTURA','BOLETA','ORDEN_COMPRA')),
  numero_comprobante  varchar(50),
  subtotal            numeric(10,2),
  igv                 numeric(10,2),
  total               numeric(10,2),
  estado              varchar(20) default 'PENDIENTE' check (estado in ('PENDIENTE','COMPLETADA','ANULADA')),
  usa_codigo_barras   boolean default false,
  ruta_documento      varchar(255),
  metodo_pago         varchar(20) check (metodo_pago in ('EFECTIVO','TARJETA','TRANSFERENCIA','YAPE','PLIN','OTROS')),
  observaciones       text,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.venta (
  id                  bigint generated by default as identity primary key,
  id_cliente          bigint not null references public.cliente(id),
  id_usuario          bigint not null references public.usuario(id),
  id_almacen          bigint not null references public.almacen(id),
  fecha               timestamptz not null default now(),
  subtotal            numeric(10,2),
  descuento_total     numeric(10,2) default 0.00,
  igv                 numeric(10,2),
  total               numeric(10,2),
  estado              varchar(20) default 'PENDIENTE' check (estado in ('PENDIENTE','COMPLETADA','ANULADA')),
  usa_codigo_barras   boolean default false,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.pedido (
  id                  bigint generated by default as identity primary key,
  id_cliente          bigint not null references public.cliente(id),
  id_venta            bigint not null references public.venta(id),
  fecha_pedido        timestamptz not null default now(),
  estado              varchar(20) default 'PENDIENTE' check (estado in ('PENDIENTE','EN_PROCESO','EN_CAMINO','ENTREGADO','CANCELADO')),
  total               numeric(10,2),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.comprobante (
  id                  bigint generated by default as identity primary key,
  id_venta            bigint not null references public.venta(id),
  tipo                varchar(20) not null check (tipo in ('BOLETA','FACTURA','NOTA_CREDITO','NOTA_DEBITO')),
  serie               varchar(10) not null,
  numero              varchar(20) not null,
  fecha_emision       timestamptz not null default now(),
  subtotal            numeric(10,2),
  igv                 numeric(10,2),
  total               numeric(10,2),
  estado              varchar(20) default 'EMITIDO' check (estado in ('EMITIDO','ANULADO')),
  ruta_pdf            varchar(255),
  ruta_xml            varchar(255),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.pago (
  id                  bigint generated by default as identity primary key,
  id_venta            bigint references public.venta(id),
  id_compra           bigint references public.compra(id),
  monto_total         numeric(10,2) not null,
  estado              varchar(20) default 'PENDIENTE' check (estado in ('PENDIENTE','PROCESANDO','COMPLETADO','FALLIDO','REEMBOLSADO')),
  fecha_pago          timestamptz not null default now(),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.detalle_pago (
  id                  bigint generated by default as identity primary key,
  id_pago             bigint not null references public.pago(id) on delete cascade,
  id_metodo_pago      bigint not null references public.metodo_pago(id),
  monto               numeric(10,2) not null,
  referencia          varchar(100),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.detalle_compra (
  id                      bigint generated by default as identity primary key,
  id_compra               bigint not null references public.compra(id) on delete cascade,
  id_producto             bigint not null references public.producto(id),
  id_codigo_barras        bigint references public.codigo_barras(id),
  cantidad                integer not null,
  precio_unitario         numeric(10,2),
  subtotal                numeric(10,2),
  registrado_con_escaner  boolean default false,
  fecha_creacion          timestamptz not null default now(),
  fecha_actualizacion     timestamptz not null default now()
);

create table public.detalle_venta (
  id                      bigint generated by default as identity primary key,
  id_venta                bigint not null references public.venta(id) on delete cascade,
  id_producto             bigint not null references public.producto(id),
  id_codigo_barras        bigint references public.codigo_barras(id),
  cantidad                integer not null,
  precio_unitario         numeric(10,2) not null,
  descuento               numeric(5,2) default 0.00,
  subtotal                numeric(10,2),
  registrado_con_escaner  boolean default false,
  fecha_creacion          timestamptz not null default now(),
  fecha_actualizacion     timestamptz not null default now()
);

create table public.devolucion (
  id                  bigint generated by default as identity primary key,
  tipo                varchar(20) not null check (tipo in ('VENTA','COMPRA')),
  id_venta            bigint references public.venta(id),
  id_compra           bigint references public.compra(id),
  id_almacen          bigint not null references public.almacen(id),
  fecha_devolucion    timestamptz not null default now(),
  motivo              text not null,
  estado              varchar(20) default 'SOLICITADA' check (estado in ('SOLICITADA','APROBADA','RECHAZADA','PROCESADA')),
  total_devolucion    numeric(10,2),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.detalle_devolucion (
  id                  bigint generated by default as identity primary key,
  id_devolucion       bigint not null references public.devolucion(id) on delete cascade,
  id_producto         bigint not null references public.producto(id),
  cantidad            integer not null,
  precio_unitario     numeric(10,2),
  subtotal            numeric(10,2),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.movimiento_inventario (
  id                  bigint generated by default as identity primary key,
  id_inventario       bigint not null references public.inventario(id) on delete cascade,
  id_producto         bigint not null references public.producto(id),
  id_almacen          bigint not null references public.almacen(id),
  id_codigo_barras    bigint references public.codigo_barras(id),
  tipo_movimiento     varchar(20) not null check (tipo_movimiento in ('ENTRADA','SALIDA','AJUSTE','DEVOLUCION')),
  cantidad            integer not null,
  stock_anterior      integer not null,
  stock_nuevo         integer not null,
  motivo              varchar(200),
  metodo_registro     varchar(20) default 'MANUAL' check (metodo_registro in ('ESCANER','MANUAL','AUTOMATICO')),
  id_usuario          bigint references public.usuario(id),
  id_compra           bigint references public.compra(id),
  id_venta            bigint references public.venta(id),
  id_devolucion       bigint references public.devolucion(id),
  fecha_movimiento    timestamptz not null default now(),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.envio (
  id                  bigint generated by default as identity primary key,
  id_pedido           bigint references public.pedido(id),
  id_venta            bigint references public.venta(id),
  id_vehiculo         bigint references public.vehiculo(id),
  id_conductor        bigint references public.conductor(id),
  id_ruta             bigint references public.ruta(id),
  direccion_envio     varchar(200),
  fecha_envio         date,
  fecha_entrega       date,
  costo_transporte    numeric(10,2),
  estado              varchar(20) default 'PENDIENTE' check (estado in ('PENDIENTE','EN_RUTA','ENTREGADO','CANCELADO')),
  observaciones       text,
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table public.historial_escaneo (
  id                  bigint generated by default as identity primary key,
  id_codigo_barras    bigint references public.codigo_barras(id),
  codigo_escaneado    varchar(50) not null,
  id_producto         bigint references public.producto(id),
  id_usuario          bigint not null references public.usuario(id),
  tipo_operacion      varchar(20) not null check (tipo_operacion in ('ENTRADA','SALIDA','CONSULTA','GENERACION')),
  id_compra           bigint references public.compra(id),
  id_venta            bigint references public.venta(id),
  cantidad            integer,
  exitoso             boolean default true,
  mensaje             varchar(255),
  fecha_escaneo       timestamptz not null default now()
);

create table public.logs_sistema (
  id                  bigint generated by default as identity primary key,
  id_usuario          bigint not null references public.usuario(id),
  accion              text,
  modulo              varchar(100),
  fecha               timestamptz not null default now(),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

-- ============================================================================
-- ÍNDICES en claves foráneas (rendimiento)
-- ============================================================================
create index idx_cliente_persona       on public.cliente(id_persona);
create index idx_conductor_persona     on public.conductor(id_persona);
create index idx_usuario_persona       on public.usuario(id_persona);
create index idx_usuario_rol           on public.usuario(id_rol);
create index idx_usuario_auth          on public.usuario(auth_user_id);
create index idx_rmp_rol               on public.role_module_permissions(id_rol);
create index idx_rmp_modulo            on public.role_module_permissions(id_modulo);
create index idx_producto_categoria    on public.producto(categoria_id);
create index idx_codbarras_producto    on public.codigo_barras(id_producto);
create index idx_provprod_proveedor    on public.proveedor_producto(id_proveedor);
create index idx_provprod_producto     on public.proveedor_producto(id_producto);
create index idx_inventario_producto   on public.inventario(id_producto);
create index idx_inventario_almacen    on public.inventario(id_almacen);
create index idx_compra_proveedor      on public.compra(id_proveedor);
create index idx_venta_cliente         on public.venta(id_cliente);
create index idx_venta_usuario         on public.venta(id_usuario);
create index idx_pedido_cliente        on public.pedido(id_cliente);
create index idx_dventa_venta          on public.detalle_venta(id_venta);
create index idx_dcompra_compra        on public.detalle_compra(id_compra);
create index idx_movinv_inventario     on public.movimiento_inventario(id_inventario);
create index idx_envio_pedido          on public.envio(id_pedido);

-- ============================================================================
-- TRIGGERS updated_at (fecha_actualizacion) en todas las tablas
-- ============================================================================
do $$
declare t text;
begin
  for t in
    select table_name from information_schema.columns
    where table_schema = 'public' and column_name = 'fecha_actualizacion'
  loop
    execute format(
      'create trigger trg_%1$s_updated before update on public.%1$s
       for each row execute function public.set_updated_at();', t);
  end loop;
end $$;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------
-- Se habilita RLS en todas las tablas y se permite acceso completo a usuarios
-- AUTENTICADOS (rol `authenticated`). Puedes endurecer estas políticas más
-- adelante por rol/usuario.
-- ============================================================================
do $$
declare t text;
begin
  for t in
    select tablename from pg_tables where schemaname = 'public'
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format(
      'create policy "authenticated_all_%1$s" on public.%1$s
       for all to authenticated using (true) with check (true);', t);
  end loop;
end $$;

-- ============================================================================
-- PUENTE CON SUPABASE AUTH
-- ----------------------------------------------------------------------------
-- Vincula automáticamente un usuario de Supabase Auth con su fila en
-- `public.usuario` haciendo match por email (persona.correo) o username.
-- Si no encuentra match, NO crea fila (debes crearla manualmente).
-- ============================================================================
create or replace function public.link_auth_user()
returns trigger language plpgsql security definer as $$
begin
  update public.usuario u
     set auth_user_id = new.id
   from public.persona p
  where u.id_persona = p.id
    and u.auth_user_id is null
    and (
      lower(p.correo) = lower(new.email)
      or lower(u.username) = lower(split_part(new.email, '@', 1))
    );
  return new;
end;
$$;

drop trigger if exists trg_link_auth_user on auth.users;
create trigger trg_link_auth_user
  after insert on auth.users
  for each row execute function public.link_auth_user();

-- ============================================================================
-- VISTAS DENORMALIZADAS (las consume el frontend para listados)
-- ============================================================================

-- Clientes con datos de persona aplanados
create or replace view public.vw_clientes as
select
  c.id                as id,
  c.id               as "clienteId",
  c.id_persona        as "idPersona",
  c.tipo              as tipo,
  c.estado            as estado,
  c.fecha_creacion    as "fechaCreacion",
  c.fecha_actualizacion as "fechaActualizacion",
  p.tipo_documento    as "tipoDocumento",
  p.numero_documento  as "numeroDocumento",
  p.nombres           as nombres,
  p.apellido_paterno  as "apellidoPaterno",
  p.apellido_materno  as "apellidoMaterno",
  p.correo            as correo,
  p.telefono          as telefono,
  p.fecha_nacimiento  as "fechaNacimiento",
  p.direccion         as direccion
from public.cliente c
join public.persona p on p.id = c.id_persona;

-- Empleados con persona + departamento
create or replace view public.vw_empleados as
select
  e.id, e.id_persona as "idPersona", e.departamento_id as "departamentoId",
  e.puesto, e.sueldo, e.fecha_contratacion as "fechaContratacion",
  e.foto, e.cv, e.estado,
  e.fecha_creacion as "fechaCreacion", e.fecha_actualizacion as "fechaActualizacion",
  p.tipo_documento as "tipoDocumento", p.numero_documento as "numeroDocumento",
  p.nombres, p.apellido_paterno as "apellidoPaterno", p.apellido_materno as "apellidoMaterno",
  p.correo, p.telefono, p.fecha_nacimiento as "fechaNacimiento", p.direccion,
  d.nombre as "departamentoNombre"
from public.empleado e
join public.persona p on p.id = e.id_persona
left join public.departamento d on d.id = e.departamento_id;

-- Productos con categoría y stock total
create or replace view public.vw_productos as
select
  pr.*,
  cp.nombre as "categoriaNombre",
  coalesce((select sum(i.stock_actual) from public.inventario i where i.id_producto = pr.id), 0) as "stockTotal"
from public.producto pr
left join public.categoria_producto cp on cp.id = pr.categoria_id;

-- Usuarios con persona y rol (para el módulo de Accesos)
create or replace view public.vw_usuarios as
select
  u.id, u.id_persona as "idPersona", u.id_rol as "idRol",
  u.username, u.estado, u.auth_user_id as "authUserId",
  u.fecha_creacion as "fechaCreacion",
  p.nombres, p.apellido_paterno as "apellidoPaterno", p.apellido_materno as "apellidoMaterno",
  p.correo, p.telefono, p.numero_documento as "numeroDocumento",
  r.nombre as "rolNombre"
from public.usuario u
join public.persona p on p.id = u.id_persona
join public.rol r on r.id = u.id_rol;

-- Las vistas se ejecutan al final, cuando todas las tablas ya existen.
-- FIN DEL ESQUEMA. A continuación ejecuta `seed.sql`.
